### ISSUE TITLE
The data file direct download link does not work

### ISSUE THREAD

**Issue by phosseini** [lrsoenksen/CL_RNA_SynthBio#1]
It looks like the direct link to download the data is broken: https://www.dropbox.com/s/731h2wudstm3zvh/Toehold_Dataset_Final_2019-10-23.csv?dl=0, error message: `This item was deleted`. May you double check the link?

**Comment by lrsoenksen** [comment]
Please use this updated link
https://drive.google.com/file/d/1t_OXvtW-hEGRt3-mgNlyBKHBqro2Z572/view?usp=sharing
